# Generated by Django 3.0.7 on 2020-12-30 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_postsub'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='postsub',
            new_name='postsub1',
        ),
    ]
