# Generated by Django 3.0.7 on 2020-12-30 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_auto_20201230_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postsub1',
            old_name='subject',
            new_name='subject1',
        ),
    ]
