# Generated by Django 3.0.7 on 2020-12-18 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event1',
            old_name='end',
            new_name='end_date_time',
        ),
        migrations.RenameField(
            model_name='event1',
            old_name='start',
            new_name='start_date_time',
        ),
    ]
