# Generated by Django 3.0.7 on 2020-12-14 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='youtuber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='media/youtubers/%Y/')),
                ('vediourl', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('topic', models.CharField(max_length=255)),
                ('chapter', models.CharField(max_length=255)),
                ('isfeatured', models.BooleanField(default=False)),
                ('createddate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
