# Generated by Django 3.0.7 on 2020-12-29 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp1', '0002_auto_20201214_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtuber',
            old_name='isfeatured',
            new_name='important',
        ),
    ]
