# Generated by Django 3.0.7 on 2020-12-30 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp1', '0006_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
