# Generated by Django 3.0.7 on 2020-12-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20201211_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='photo',
            field=models.ImageField(upload_to='media/slider/%Y/'),
        ),
    ]
