# Generated by Django 3.0.7 on 2020-12-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20201214_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='link',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
