# Generated by Django 3.0.7 on 2020-12-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ytube',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
