# Generated by Django 3.0.7 on 2020-12-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_team_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='likes',
        ),
    ]
