# Generated by Django 3.0.7 on 2020-12-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_team_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='flink',
            new_name='conceptlink',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='fname',
            new_name='conceptname',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='ilink',
            new_name='platform',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='team',
            name='role',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ytube',
        ),
    ]
